version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: lambda
      LAMBDA_EXECUTOR: docker
      LAMBDA_REMOVE_CONTAINERS: 'false'
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  localstack-data: